spring.application.name=demo
spring.datasource.url=jdbc:postgresql://dpg-d6g15adm5p6s7393jh0g-a.oregon-postgres.render.com:5432/myapp_1vxx
spring.datasource.username=myapp_1vxx_user
spring.datasource.password=BTUEi0O5iR7litF5365MvJV9USj0V0LC
spring.jpa.hibernate.ddl-auto=update
server.port=8080
